apiVersion: v1
data:
  mapRoles: |
    - rolearn: arn:aws:iam::685448855545:role/eks-node-role-new
      groups:
      - system:bootstrappers
      - system:nodes
      username: system:node:{{EC2PrivateDNSName}}

  mapUsers: |
    - userarn: arn:aws:iam::685448855545:user/Capstone-project
      username: Capstone-project
      groups:
      - system:masters

kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system