apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatbot-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: 685448855545.dkr.ecr.us-east-1.amazonaws.com/chatbot-frontend:latest
        ports:
        - containerPort: 80