apiVersion: apps/v1
kind: Deployment
metadata:
  name: stress-test
spec:
  replicas: 2
  selector:
    matchLabels:
      app: stress
  template:
    metadata:
      labels:
        app: stress
    spec:
      containers:
      - name: stress-container
        image: polinux/stress
        command: ["stress"]
        args: ["--cpu", "4", "--timeout", "300s"]

        resources:
          requests:
            cpu: "500m"
            memory: "200Mi"
          limits:
            cpu: "1000m"
            memory: "500Mi"